So far, we have only subscribed to the pre-defined Observables. We haven't tried to create one ourselves.

As mentioned in the previous section, Observables are not something that Angular provides but they are a feature offered by RxJS library.

The RxJS library offers a ton of functions to use and one such function is "interval" which lets us define some value (in milliseconds) and then it will return a number (starting from 0) every "x" milliseconds that we defined.

This is a good way to visualize how the Observables work by emitting values over time.

    import {interval} from 'rxjs';
    interval(1000).subscribe({
      next: count => {console.log(count)}
    })

So, 1000 here means that every "1" second, emit a number that keeps incrementing in each emission. So, initially, "0" gets emitted. Then after 1 second, "1" gets emitted, then "2" and so on.

And this emitted value is something we can then subscribe to because "interval" method returns an Observable.

And since we are subscribing to it, as the new values get emitted, the code inside "next" block keeps executing automatically.

It is also worth mentioning that if we do not subscribe, then the Observable will not do anything.

That is, if we just say -   

        interval(1000)

Then, nothing will happen since Observables are lazy, meaning if no one subscribes to them, nothing happens.

But, another thing to keep in mind is that when we subscribe to an observable, we also have to unsubscribe to it when we don't want to use it anymore. Otherwise, the observable will still keep emitting values and the function inside "next" keeps getting called, even if we don't need it.

We can notice that if we put the interval() code inside any component and then navigate away from that component. The code inside subscribe will still keep running. This is going to affect the performance. 

So, the observables won't stop emitting the values if we don't want the values anymore. We have to explicitly tell them. 

Every observable "subscribe" method returns a "Subscription" object and that object has the "unsubscribe" method attached to it that we can call anytime we want to stop getting the values. Usually, the best place to do this is when we navigate away from the current component, inside the ngOnDestroy method.

    sub : Subscription;
    ngOnInit() {
        this.sub = interval(1000).subscribe({
        next: count => {console.log(count)}
        })
    }

    ngOnDestroy() {
        this.sub.unsubscribe();
    }

Again, note that we are not storing the actual observable in the "sub" variable. Instead, we are storing the "Subscription" that gets returned whenever "subscribe" is called.

Note that in case of the Router related observables like "params", "paramMap", "data", "fragment" etc, Angular automatically unsubscribes to them when the component gets destroyed.


# CREATING A CUSTOM OBSERVABLE

In above example, we did not create our own observable and we just used a built-in one.

So, let's now create one from scratch. Or better, let's create the same thing as what "interval" does.

To create a custom observable, we can use the "Observable" constructor. This is same as creating an object of any class.

This "Observable" constructor takes in a callback function with one argument of type "Subscriber" which simply refers to anything that will subscribe to this observable. To keep things simple, let's call this argument as "observer". 

And now, all that we have to do is just emit the data that we want.

Here, we want to replicate what the interval method was doing. That is, emit an incremented number every second. And we can do that using setInterval method.

    const customIntervalObs = new Observable(observer => {
      let data = 0;
      setInterval(() => {
        observer.next(data++);
      }, 1000)
    });

And now, we have created a custom Observable from scratch that does the same thing as "interval()" method from rxjs.

Again, we also have to take care of unsubscribing to this custom observable because otherwise, it will keep emitting the data even when the component where we subscribed has been destroyed.

    ngOnDestroy() {
       this.customSub.unsubscribe();
    }

# ERRORS & COMPLETION

Note that observer.next() is used to emit something that we can then handle in the "next" block of "subscribe" method.

Similarly, to emit an error, we can say observer.error() and to complete this observable, we can say observer.complete();

The most common case where we would need to handle the "error" scenarios is in case of http requests. Because, in Angular, the httpClient also gives us an Observable when we make an http request. So, it is not always possible that we get a success response. We might get some error response too. So, we also have to handle it.

In our custom observable that we created above, there is no change of failure since we are simply passing an incremented value.

So, even if we have an "error" block when we subscribe to it, that error block never runs since there will never be an error.

But, we can throw an error ourselves. Let's say if the count exceeds 3, then we want to throw an error.


    const customIntervalObs = new Observable(observer => {
        let data = 0;
        setInterval(() => {
            if (data > 3) {
            observer.error("Invalid Number")
            }
            observer.next(data++);
        }, 1000)
        });

So now, our "next" block will keep running till "3" but as soon as the observable emits "4", the "error" block is then executed since an error is thrown.

    this.customSub = customIntervalObs.subscribe({
      next: data => console.log("Data received", data),
      error: err => console.log("Error", err)
    })

You will also see that as soon as an error is emitted, the observable then stops emitting any data or error. Otherwise, it should have kept emitting "4", "5", "6" and the error block should've kept running. But the error block ran only once.

And this means, even if we write observer.complete() after we emit an error, that complete block will never be called since hte observable ended before that.

    const customIntervalObs = new Observable(observer => {
      let data = 0;
      setInterval(() => {
        if (data > 3) {
          observer.error("Invalid Number")
          observer.complete();
        }
        observer.next(data++);
      }, 1000)
    });

    this.customSub = customIntervalObs.subscribe({
      next: data => console.log("Data received", data),
      error: err => console.log("Error", err),
      complete: () => console.log("Observable Completed")
    })

So, in above case, the "complete" block never gets called since the observable ended as soon as "error" was emitted.

Let's talk about the final thing that the Observable can give us and that's "complete". We can mark an observable as "complete" when we know that the work is done. 

Ofcourse, it does not mean that every observable has to complete. In our case, if we don't emit an error, out observable will keep emitting the data indefinitely. It will never complete. So, there are observables that never complete.

For example, if there is an observable attached to a button on the UI, how does it know when to complete? The user can click the button any time.

An example of ab observable that will definitely complete is an HTTP request. As soon as a response is returned, its job is done.

Let's say as soon as we emit "3", our observable is then complete and so no more values should be emitted.

In this case, we can call the "complete" method on the observer.

    const customIntervalObs = new Observable(observer => {
      let data = 0;
      setInterval(() => {
        if (data > 3) {
          observer.complete();
        }
        if (data > 3) {
          observer.error("Invalid Number")
        }
        observer.next(data++);
      }, 1000)
    });

    this.customSub = customIntervalObs.subscribe({
      next: data => console.log("Data received", data),
      error: err => console.log("Error", err),
      complete: () => console.log("Observable Completed")
    })

We will see that even though we have the if condition that emits an error if data is > 3, the "error" block still does not get called because before it, we have already completed the observable.

So, it is important to understand that "complete" is different than "error". If an "error" gets emitted, the observable stops and if the "complete" gets emitted, then also observable stops.

But, when we subscribe to the observable, these two are treated differently.

# UNDERSTANDING HOW DATA IS PASSED BETWEEN SUBSCRIBE AND OBSERVABLE DEFINITION

After all that we learned, we see that some things are common in "subscribe" and the observable definition. These are "next", "error" and "complete".

The thing is, when we call the "subscribe" method and then pass the object to it with keys are "next", "error" and "complete", then this object is the one that gets mapped to that "observer" which we pass as argument to the observable.

  const customIntervalObs = new Observable(observer => {
      let data = 0;
      setInterval(() => {
        if (data > 3) {
          observer.complete();
        }
        if (data > 3) {
          observer.error("Invalid Number")
        }
        observer.next(data++);
      }, 1000)
    });


    this.customSub = customIntervalObs.subscribe({
      next: data => console.log("Data received", data),
      error: err => console.log("Error", err),
      complete: () => console.log("Observable Completed")
    })

In above code, the object we passed to subscribe is this - 

    {
      next: data => console.log("Data received", data),
      error: err => console.log("Error", err),
      complete: () => console.log("Observable Completed")
    }

And so, the observable then gets this object as the arugment named "observer". And that's the reason why "observer" can access these keys as "observer.next()", "observer.error()" and "observer.complete()". 

And that's how an observable works under the hood.